### ISSUE TITLE
License

### ISSUE THREAD

**Issue by richiejp** [danieljiang0415/android_kernel_crash_poc#1]
Hi, 

I assume this is public domain or that in any case you do not mind me using it as the basis for an LTP test under GPL?

**Comment by danieljiang0415** [comment]
Hi,

It's OK, you can do any thing if you want. ^_^

2017-04-24 20:51 GMT+08:00 Richard Palethorpe <notifications@github.com>:

**Comment by richiejp** [comment]
Thanks :-)
